const SUPPORTED_EXTENSIONS_WITH_COMMA = [
  '.pdf',
];

const SUPPORTED_EXTENSIONS_WITHOUT_COMMA =
  SUPPORTED_EXTENSIONS_WITH_COMMA
  .map((ext: string) => ext.slice(1));

export {
  SUPPORTED_EXTENSIONS_WITH_COMMA,
  SUPPORTED_EXTENSIONS_WITHOUT_COMMA,
};
