name: test
on:
  push:
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Copy Files
      run: yarn copy-files
    - name: Run tests
      run: yarn test
